services:
  - type: web
    name: healthbridge-ml
    runtime: docker
    rootDir: ml-service
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ENABLE_LLM_SYMPTOM
        value: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant

  - type: web
    name: healthbridge-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES
        value: 30d
      - key: FRONTEND_URL
        sync: false
      - key: FRONTEND_URLS
        sync: false
      - key: ML_SERVICE_URL
        sync: false
      - key: SEED_DEMO_DOCTORS
        value: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false

  - type: web
    name: healthbridge-frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3003
      - key: BACKEND_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
